project 'YapDatabaseTesting.xcodeproj'
platform :ios, '10.0'
use_modular_headers!

target 'YapDatabase' do
	pod "YapDatabase", path: '../../'
end

target 'YapDatabaseTests' do
	pod "YapDatabase", path: '../../'
end
