source 'https://github.com/CocoaPods/Specs.git'

workspace 'YapDatabaseTesting'
project 'YapDatabaseTesting.xcodeproj'

use_modular_headers!

target :'YapDatabaseTesting' do

	platform :ios, '9.0'

	pod "YapDatabase", path: '../../'
end
	
abstract_target 'watchOS' do
	
	pod "YapDatabase", path: '../../'

	target :'YapDatabaseTesting WatchKit App' do
		platform :watchos, '3.0'
	end
	
	target :'YapDatabaseTesting WatchKit Extension' do
		platform :watchos, '3.0'
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
			config.build_settings.delete 'MACOSX_DEPLOYMENT_TARGET'
		end
	end
end
