project 'YapDatabaseTesting.xcodeproj'

# Workaround for Xcode bug:
# - https://www.ralfebert.de/ios/blog/cocoapods-clean-input-output-files/
# - https://github.com/CocoaPods/CocoaPods/issues/8073
# - https://github.com/CocoaPods/CocoaPods/pull/8105
# 
install! 'cocoapods', :disable_input_output_paths => true

abstract_target 'macOS' do
	platform :osx, '10.12'
	use_frameworks!

	pod "YapDatabase/Standard-ObjC", path: '../../'

	target 'YapDatabase' do
	end

	target 'YapDatabaseTests' do
	end

	target 'MultiprocessApp' do
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
			config.build_settings.delete 'MACOSX_DEPLOYMENT_TARGET'
		end
	end
end
