project 'YapDatabaseTesting.xcodeproj'
platform :osx, '10.12'

target 'YapDatabase' do
	pod "YapDatabase", path: '../../'
end

target 'YapDatabaseTests' do
	pod "YapDatabase", path: '../../'
end

target 'MultiprocessApp' do
	pod "YapDatabase", path: '../../'
end
