project 'YapDatabaseTesting.xcodeproj'

abstract_target 'macOS' do
	platform :osx, '10.12'

	pod "YapDatabase", path: '../../'

	target 'YapDatabase' do
	end

	target 'YapDatabaseTests' do
	end

	target 'MultiprocessApp' do
	end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
			config.build_settings.delete 'MACOSX_DEPLOYMENT_TARGET'
		end
	end
end
