# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-desktop' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	# Pods for Swift-desktop
	pod "YapDatabase/Standard-Swift", path: '../../'

end
