project 'YapDatabaseTesting.xcodeproj'
platform :tvos, '9.0'

target 'YapDatabase' do
	pod "YapDatabase", path: '../../'
end

target 'YapDatabaseTests' do
	pod "YapDatabase", path: '../../'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
			config.build_settings.delete 'MACOSX_DEPLOYMENT_TARGET'
		end
	end
end
